#query nome_da_query {
#  fields
#}
#
#query get {
#  hello
#  id
#  age
#  average
#  isMarried
#  isAlive
#  arrayString
#  arrayStringNull
#}

# Em queries de custom types, é obrigatório especificar os campos desejados
query get_user {
  user (id: "602"){
    id
    __typename # Type
  }
}

# Query com passagem de parâmetros

query get {
  user(id: "2") {
    userName
  }
}

# Query variables em queries dinâmicas
query get_user_by_id ($id: ID! = "812") {  # "812" é um valor padrão
    user (id: $id) {
        id
        userName
        firstName
        lastName
    }
}

query get_user_by_id ($id: ID!) { # Sem valor padrão
    user (id: $id) {
        id
        userName
        firstName
        lastName
    }
}

query get_user_by_id ($id: ID!, $teste: Boolean) {
    user (id: $id, teste: $teste) {
        id
        userName
        firstName
        lastName
    }
}


# Alias de queries
query get {
    post860:post(id:860){
        postId:id
        id
        title
    }
    post(id:940){
        id
        title
    }
}


# Queries fragments. Se declarado, o uso é obrigatório
fragment postFragment on Post {
    id
    title
    body
}

query get {
    post1: post(id:860){
        ...postFragment
        unixTimestamp
    }
    post2: post(id:940){
        ...postFragment
        createdAt
    }
    post3: post(id:342){
        ...postFragment
        indexRef
    }
}